[package]
name = "path_find"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# random numbers
rand = "0.8.5"

# 2d rendering and windowing
notan = "0.5.1"